/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DigitalTrustRouteImport } from './routes/digital-trust'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as SegmentsIndexRouteImport } from './routes/segments.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PlatformsIndexRouteImport } from './routes/platforms.index'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as ConsultingIndexRouteImport } from './routes/consulting.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SegmentsSlugRouteImport } from './routes/segments.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PlatformsSlugRouteImport } from './routes/platforms.$slug'
import { Route as PartnersSlugRouteImport } from './routes/partners.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ConsultingSlugRouteImport } from './routes/consulting.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as AboutSlugRouteImport } from './routes/about.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTrustRoute = DigitalTrustRouteImport.update({
  id: '/digital-trust',
  path: '/digital-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsIndexRoute = SegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsIndexRoute = PlatformsIndexRouteImport.update({
  id: '/platforms/',
  path: '/platforms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingIndexRoute = ConsultingIndexRouteImport.update({
  id: '/consulting/',
  path: '/consulting/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsSlugRoute = SegmentsSlugRouteImport.update({
  id: '/segments/$slug',
  path: '/segments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsSlugRoute = PlatformsSlugRouteImport.update({
  id: '/platforms/$slug',
  path: '/platforms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersSlugRoute = PartnersSlugRouteImport.update({
  id: '/partners/$slug',
  path: '/partners/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingSlugRoute = ConsultingSlugRouteImport.update({
  id: '/consulting/$slug',
  path: '/consulting/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSlugRoute = AboutSlugRouteImport.update({
  id: '/about/$slug',
  path: '/about/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/digital-trust': typeof DigitalTrustRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/consulting/$slug': typeof ConsultingSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/partners/$slug': typeof PartnersSlugRoute
  '/platforms/$slug': typeof PlatformsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/segments/$slug': typeof SegmentsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/consulting/': typeof ConsultingIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/platforms/': typeof PlatformsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/segments/': typeof SegmentsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/digital-trust': typeof DigitalTrustRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/consulting/$slug': typeof ConsultingSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/partners/$slug': typeof PartnersSlugRoute
  '/platforms/$slug': typeof PlatformsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/segments/$slug': typeof SegmentsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/about': typeof AboutIndexRoute
  '/careers': typeof CareersIndexRoute
  '/consulting': typeof ConsultingIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/platforms': typeof PlatformsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/segments': typeof SegmentsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/digital-trust': typeof DigitalTrustRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/consulting/$slug': typeof ConsultingSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/partners/$slug': typeof PartnersSlugRoute
  '/platforms/$slug': typeof PlatformsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/segments/$slug': typeof SegmentsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/consulting/': typeof ConsultingIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/platforms/': typeof PlatformsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/segments/': typeof SegmentsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/digital-trust'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/about/$slug'
    | '/careers/$slug'
    | '/consulting/$slug'
    | '/insights/$slug'
    | '/partners/$slug'
    | '/platforms/$slug'
    | '/products/$slug'
    | '/segments/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/about/'
    | '/careers/'
    | '/consulting/'
    | '/insights/'
    | '/partners/'
    | '/platforms/'
    | '/products/'
    | '/segments/'
    | '/services/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/digital-trust'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/about/$slug'
    | '/careers/$slug'
    | '/consulting/$slug'
    | '/insights/$slug'
    | '/partners/$slug'
    | '/platforms/$slug'
    | '/products/$slug'
    | '/segments/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/about'
    | '/careers'
    | '/consulting'
    | '/insights'
    | '/partners'
    | '/platforms'
    | '/products'
    | '/segments'
    | '/services'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/digital-trust'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/about/$slug'
    | '/careers/$slug'
    | '/consulting/$slug'
    | '/insights/$slug'
    | '/partners/$slug'
    | '/platforms/$slug'
    | '/products/$slug'
    | '/segments/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/about/'
    | '/careers/'
    | '/consulting/'
    | '/insights/'
    | '/partners/'
    | '/platforms/'
    | '/products/'
    | '/segments/'
    | '/services/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DigitalTrustRoute: typeof DigitalTrustRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AboutSlugRoute: typeof AboutSlugRoute
  CareersSlugRoute: typeof CareersSlugRoute
  ConsultingSlugRoute: typeof ConsultingSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  PartnersSlugRoute: typeof PartnersSlugRoute
  PlatformsSlugRoute: typeof PlatformsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  SegmentsSlugRoute: typeof SegmentsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ConsultingIndexRoute: typeof ConsultingIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  PlatformsIndexRoute: typeof PlatformsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SegmentsIndexRoute: typeof SegmentsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-trust': {
      id: '/digital-trust'
      path: '/digital-trust'
      fullPath: '/digital-trust'
      preLoaderRoute: typeof DigitalTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/': {
      id: '/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof SegmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms/': {
      id: '/platforms/'
      path: '/platforms'
      fullPath: '/platforms/'
      preLoaderRoute: typeof PlatformsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting/': {
      id: '/consulting/'
      path: '/consulting'
      fullPath: '/consulting/'
      preLoaderRoute: typeof ConsultingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/$slug': {
      id: '/segments/$slug'
      path: '/segments/$slug'
      fullPath: '/segments/$slug'
      preLoaderRoute: typeof SegmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms/$slug': {
      id: '/platforms/$slug'
      path: '/platforms/$slug'
      fullPath: '/platforms/$slug'
      preLoaderRoute: typeof PlatformsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$slug': {
      id: '/partners/$slug'
      path: '/partners/$slug'
      fullPath: '/partners/$slug'
      preLoaderRoute: typeof PartnersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting/$slug': {
      id: '/consulting/$slug'
      path: '/consulting/$slug'
      fullPath: '/consulting/$slug'
      preLoaderRoute: typeof ConsultingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$slug': {
      id: '/about/$slug'
      path: '/about/$slug'
      fullPath: '/about/$slug'
      preLoaderRoute: typeof AboutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DigitalTrustRoute: DigitalTrustRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AboutSlugRoute: AboutSlugRoute,
  CareersSlugRoute: CareersSlugRoute,
  ConsultingSlugRoute: ConsultingSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  PartnersSlugRoute: PartnersSlugRoute,
  PlatformsSlugRoute: PlatformsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  SegmentsSlugRoute: SegmentsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  ConsultingIndexRoute: ConsultingIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  PlatformsIndexRoute: PlatformsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SegmentsIndexRoute: SegmentsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
